
/**
 *   This is a autogenerated file that is created by parsig op-code files
 *   To regenerate it use 
 * 
 *   ts-node scripts/scan_opcodes.ts
 **/ 

export class ContractOpcodes {
    static JETTON_PROVIDE_WALLET_ADDRESS : number = 0x2c76b973 // 745978227
    static JETTON_TAKE_WALLET_ADDRESS : number = 0xd1735400 // 3513996288
    static JETTON_TRANSFER       : number = 0xf8a7ea5 // 260734629
    static JETTON_TRANSFER_NOTIFICATION : number = 0x7362d09c // 1935855772
    static JETTON_INTERNAL_TRANSFER : number = 0x178d4519 // 395134233
    static JETTON_EXCESSES       : number = 0xd53276db // 3576854235
    static JETTON_BURN           : number = 0x595f07bc // 1499400124
    static JETTON_BURN_NOTIFICATION : number = 0x7bdd97de // 2078119902
    static JETTON_MINT           : number = 0x15 // 21
    static NFT_TRANSFER          : number = 0x5fcc3d14 // 1607220500
    static NFT_OWNERSHIP_ASSIGNED : number = 0x5138d91 // 85167505
    static NFT_EXCESSES          : number = 0xd53276db // 3576854235
    static NFT_GET_STATIC_DATA   : number = 0x2fcb26a2 // 801842850
    static NFT_REPORT_STATIC_DATA : number = 0x8b771735 // 2339837749
    static NFT_GET_ROYALTY_PARAMS : number = 0x693d3950 // 1765620048
    static NFT_REPORT_ROYALTY_PARAMS : number = 0xa8cb00ad // 2831876269
    static NFT_EDIT_CONTENT      : number = 0x1a0b9d51 // 436968785
    static NFT_TRANSFER_EDITORSHIP : number = 0x1c04412a // 470040874
    static NFT_EDITORSHIP_ASSIGNED : number = 0x511a4463 // 1360675939
    static POOLV3_INIT           : number = 0xc674e474 // 3329549428
    static POOLV3_SWAP           : number = 0x25938561 // 630424929
    static POOLV3_MINT           : number = 0x318f361 // 51966817
    static POOLV3_BURN           : number = 0x55521d04 // 1431444740
    static POOLV3_COLLECT        : number = 0xa40662f4 // 2751881972
    static POOLV3_SET_POOL       : number = 0x3a564b0f // 978733839
    static ROUTERV3_PAY_TO       : number = 0xf93bb43f // 4181439551
    static ROUTERV3_TRANSFER_NOTIFICATION : number = 0xf189f909 // 4052351241
    static ROUTERV3_SET_POOL     : number = 0x3a564b0f // 978733839
    static SINKV3_SET            : number = 0xe61425dc // 3860080092
    static SINKV3_ADD            : number = 0xfd1a73e7 // 4246369255
}

export const OpcodesLookup = {    
    0x15 : "JETTON_MINT",
    0x318f361 : "POOLV3_MINT",
    0x5138d91 : "NFT_OWNERSHIP_ASSIGNED",
    0xf8a7ea5 : "JETTON_TRANSFER",
    0x178d4519 : "JETTON_INTERNAL_TRANSFER",
    0x1a0b9d51 : "NFT_EDIT_CONTENT",
    0x1c04412a : "NFT_TRANSFER_EDITORSHIP",
    0x25938561 : "POOLV3_SWAP",
    0x2c76b973 : "JETTON_PROVIDE_WALLET_ADDRESS",
    0x2fcb26a2 : "NFT_GET_STATIC_DATA",
    0x3a564b0f : "POOLV3_SET_POOL,ROUTERV3_SET_POOL",
    0x511a4463 : "NFT_EDITORSHIP_ASSIGNED",
    0x55521d04 : "POOLV3_BURN",
    0x595f07bc : "JETTON_BURN",
    0x5fcc3d14 : "NFT_TRANSFER",
    0x693d3950 : "NFT_GET_ROYALTY_PARAMS",
    0x7362d09c : "JETTON_TRANSFER_NOTIFICATION",
    0x7bdd97de : "JETTON_BURN_NOTIFICATION",
    0x8b771735 : "NFT_REPORT_STATIC_DATA",
    0xa40662f4 : "POOLV3_COLLECT",
    0xa8cb00ad : "NFT_REPORT_ROYALTY_PARAMS",
    0xc674e474 : "POOLV3_INIT",
    0xd1735400 : "JETTON_TAKE_WALLET_ADDRESS",
    0xd53276db : "JETTON_EXCESSES,NFT_EXCESSES",
    0xe61425dc : "SINKV3_SET",
    0xf189f909 : "ROUTERV3_TRANSFER_NOTIFICATION",
    0xf93bb43f : "ROUTERV3_PAY_TO",
    0xfd1a73e7 : "SINKV3_ADD",
}
export class ContractErrors {
    static COMMON_WRONG_OP       : number = 65535 // 0x{valueHex}
    static JETTON_NOT_ADMIN_TO_MINT : number = 73 // 0x{valueHex}
    static NFT_NOT_OWNER         : number = 401 // 0x{valueHex}
    static POOLV3_NO_LIQUIDITY   : number = 80 // 0x{valueHex}
    static POOLV3_ZERO_OUTPUT    : number = 81 // 0x{valueHex}
    static POOLV3_INVALID_CALLER : number = 82 // 0x{valueHex}
    static POOLV3_INSUFFICIENT_GAS : number = 83 // 0x{valueHex}
    static POOLV3_FEE_OUT_RANGE  : number = 85 // 0x{valueHex}
    static POOLV3_INVALID_TOKEN  : number = 86 // 0x{valueHex}
    static POOLV3_LOW_AMOUNT     : number = 87 // 0x{valueHex}
    static POOLV3_LOW_LIQUIDITY  : number = 88 // 0x{valueHex}
    static POOLV3_WRONG_K        : number = 89 // 0x{valueHex}
    static POOLV3_MATH_ERROR     : number = 90 // 0x{valueHex}
    static POOLV3_INVALID_RECIPIENT : number = 91 // 0x{valueHex}
    static POOLV3_TICK_IMPOSSIBLE_LOW : number = 100 // 0x{valueHex}
    static POOLV3_TICK_IMPOSSIBLE_HIGH : number = 101 // 0x{valueHex}
    static POOLV3_PRICE_IMPOSSIBLE_LOW : number = 102 // 0x{valueHex}
    static POOLV3_PRICE_IMPOSSIBLE_HIGH : number = 103 // 0x{valueHex}
    static POOLV3_PRICE_LIMIT_WRONG : number = 106 // 0x{valueHex}
    static POOLV3_POOL_INACTIVE  : number = 104 // 0x{valueHex}
    static POOLV3_TOO_MUCH_LIQUIDITY : number = 105 // 0x{valueHex}
    static ROUTERV3_INVALID_AMOUNT : number = 110 // 0x{valueHex}
}

export const ErrorsLookup = {    
    73 : "JETTON_NOT_ADMIN_TO_MINT",
    80 : "POOLV3_NO_LIQUIDITY",
    81 : "POOLV3_ZERO_OUTPUT",
    82 : "POOLV3_INVALID_CALLER",
    83 : "POOLV3_INSUFFICIENT_GAS",
    85 : "POOLV3_FEE_OUT_RANGE",
    86 : "POOLV3_INVALID_TOKEN",
    87 : "POOLV3_LOW_AMOUNT",
    88 : "POOLV3_LOW_LIQUIDITY",
    89 : "POOLV3_WRONG_K",
    90 : "POOLV3_MATH_ERROR",
    91 : "POOLV3_INVALID_RECIPIENT",
    100 : "POOLV3_TICK_IMPOSSIBLE_LOW",
    101 : "POOLV3_TICK_IMPOSSIBLE_HIGH",
    102 : "POOLV3_PRICE_IMPOSSIBLE_LOW",
    103 : "POOLV3_PRICE_IMPOSSIBLE_HIGH",
    104 : "POOLV3_POOL_INACTIVE",
    105 : "POOLV3_TOO_MUCH_LIQUIDITY",
    106 : "POOLV3_PRICE_LIMIT_WRONG",
    110 : "ROUTERV3_INVALID_AMOUNT",
    401 : "NFT_NOT_OWNER",
    65535 : "COMMON_WRONG_OP",
}